"""Connective-CPPN spike substrate (ai/cppn_spike_plan.md): a generative encoding prototype.

The evolved genome IS a CPPN: an ordinary `Genome` (1 input + bias -> 4 outputs) run through the
ordinary `GraphNet`. The phenotype is a bank of `H` detectors at coordinates evenly spaced on
[-1, 1] (an abstract index continuum, never a hand-designed spatial grid): one CPPN forward over
the coordinates emits each detector's parameters (w_x, w_y, w_bias, w_out), and the phenotype
logit is computed as tensor ops ON those outputs, so the entire pipe is differentiable and the
existing `gradient` op trains the CPPN's weights through the task loss.

LOAD-BEARING CONTRACT: the expansion runs INSIDE `CppnPhenotypeNet.forward` on every call, never
cached at decode. A decode-time cache breaks the second Adam step (backward through a freed graph,
which `Evolver.assess` does not catch) and silently fakes the `weight_samples` generator
diagnostic (the sweep fills CPPN weights; a cached phenotype would never change).

v0 scope, per the plan: the detector bank hard-codes input arity 2 (the two-spirals x, y); `H`
and the phenotype activation are run parameters, not genes; depth and the general pair-query form
are behind gate E.
"""

import math
from dataclasses import dataclass

import torch

from versal.dataset.icarus import Axis, EncodedTask, Field, Level0Encoder, Task, TaskKind, TaskMeta, ValueType
from versal.evaluation import evaluate, output_features
from versal.evolution.genome import ConnectionGene, Genome, NodeGene, NodeKind
from versal.substrate import _ACTIVATIONS, GraphNet, SubstrateModule, decode

# The CPPN's I/O shape: f(c) -> (w_x, w_y, w_bias, w_out_1..w_out_k) where k is the TASK's logit
# width (1 for a BINARY target, n_classes for CATEGORICAL; the real rung-3 task is CATEGORICAL(2)).
CPPN_INPUTS = 1
CPPN_PARAM_OUTPUTS = 3  # w_x, w_y, w_bias; the readout head adds k more


def cppn_output_count(n_logits: int) -> int:
    return CPPN_PARAM_OUTPUTS + n_logits


def detector_coordinates(h: int) -> torch.Tensor:
    """The abstract detector index continuum: `h` coordinates evenly spaced on [-1, 1]."""
    return torch.linspace(-1.0, 1.0, h).unsqueeze(1)


class CppnPhenotypeNet(SubstrateModule):
    """A detector bank whose parameters are generated by the inner CPPN at every forward.

    `parameters()` yields the CPPN's weights (the inner `GraphNet` is a registered submodule), so
    `gradient` trains the GENERATOR through the task loss, the `weight_samples` sweep interrogates
    the generator's structure, and Lamarckian writeback lands on the CPPN genome through the
    ordinary `export_weights` contract.
    """

    def __init__(self, cppn: GraphNet, h: int, phenotype_activation: str, n_logits: int = 1) -> None:
        super().__init__()
        self.cppn = cppn
        self.h = h
        self.phenotype_activation = phenotype_activation
        self.n_logits = n_logits
        self._activation = _ACTIVATIONS[phenotype_activation]
        self._coordinates = detector_coordinates(h)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.dim() != 2 or x.shape[1] != 2:
            raise ValueError(f"v0 detector bank is arity-2 (two-spirals x, y); got input shape {tuple(x.shape)}")
        parameters = self.cppn(self._coordinates)  # [H, 3 + k], regenerated every call (see module docstring)
        pre_activation = x[:, 0:1] * parameters[:, 0].unsqueeze(0) + x[:, 1:2] * parameters[:, 1].unsqueeze(0) + parameters[:, 2].unsqueeze(0)
        detectors = self._activation(pre_activation)  # [B, H]
        return detectors @ parameters[:, CPPN_PARAM_OUTPUTS : CPPN_PARAM_OUTPUTS + self.n_logits]  # [B, k]: the task's logit contract

    @property
    def has_edges(self) -> bool:
        return self.cppn.has_edges

    def export_weights(self) -> dict[tuple[int, int, bool], float]:
        return self.cppn.export_weights()

    def re_expanded(self, h: int) -> "CppnPhenotypeNet":
        """The same generator at a different resolution: the transfer measurement's lever."""
        return CppnPhenotypeNet(self.cppn, h, self.phenotype_activation, self.n_logits)


@dataclass
class CppnTaskAdapter:
    """Evolver `Adapter` whose decode expands a CPPN genome into a detector-bank phenotype.

    `n_inputs`/`n_outputs` are the CPPN's shape (so `init.minimal` and every mutator size the
    GENERATOR, not the task); `evaluate` scores the expanded phenotype against the encoded task.
    """

    encoded: EncodedTask
    encoder: Level0Encoder
    h: int
    phenotype_activation: str
    n_inputs: int = CPPN_INPUTS
    n_outputs: int = 0  # derived from the task's logit width in __post_init__

    def __post_init__(self) -> None:
        if self.n_outputs <= 0:
            self.n_outputs = cppn_output_count(output_features(self.encoded))

    @property
    def n_logits(self) -> int:
        return self.n_outputs - CPPN_PARAM_OUTPUTS

    def decode(self, genome: Genome) -> CppnPhenotypeNet:
        return CppnPhenotypeNet(decode(genome, self.n_inputs, self.n_outputs), self.h, self.phenotype_activation, self.n_logits)

    def evaluate(self, module: SubstrateModule) -> dict[str, float]:
        return evaluate(module, self.encoded, self.encoder)


def synthetic_two_spirals_task(*, turns: float = 3.0, n_samples: int = 400, support_fraction: float = 0.8) -> Task:
    """The pinned offline two-spirals set, mirroring rung-3 geometry and the `[dataset]` split.

    Classic Archimedean construction: arm points at r = (t_max - t)/t_max, phi = t * pi / 16 with
    t on [0, 32 * turns] (so phi spans `turns` full turns), the second arm mirrored through the
    origin. The support/query split is a deterministic stride (every 5th point to query at the
    default 0.8), so the fixture and the E0 gate are bitwise-reproducible with no rng.
    """
    per_arm = n_samples // 2
    t_max = 32.0 * turns
    offsets = torch.tensor([t_max * index / (per_arm - 1) for index in range(per_arm)])
    radius = (t_max + 8.0 - offsets) / (t_max + 8.0)  # +8 keeps the innermost points off the exact origin
    phi = offsets * math.pi / 16.0
    arm = torch.stack([radius * torch.sin(phi), radius * torch.cos(phi)], dim=1)

    query_every = max(2, round(1.0 / max(1.0 - support_fraction, 1e-9)))
    support_pairs: list[tuple[Field, Field]] = []
    query_pairs: list[tuple[Field, Field]] = []
    for index in range(per_arm):
        for point, label in ((arm[index], 1.0), (-arm[index], 0.0)):
            x = Field(point.clone(), (Axis.EXTRA,), ValueType.CONTINUOUS, None, None, None)
            y = Field(torch.tensor([label]), (Axis.EXTRA,), ValueType.BINARY, None, None, None)
            (query_pairs if index % query_every == query_every // 2 else support_pairs).append((x, y))
    meta = TaskMeta(rung=3, kind=TaskKind.MAP, name="two_spirals_synthetic", fixed_split=True)
    return Task(meta=meta, support=support_pairs, query=query_pairs)


def fourier_cppn_genome(*, m: int = 3, seed: int = 0, coefficient_scale: float = 3.0, n_logits: int = 1) -> Genome:
    """The hand-built existence topology (gate E0): per-output Fourier curves in c.

    2m sin-activated hidden nodes form quadrature pairs (sin(pi k c) and, via a pi/2 bias phase,
    cos(pi k c)); every output reads all pairs plus a bias constant, so each generated parameter
    is a free Fourier series of order m in the detector coordinate. Frequencies and phases are
    hand-set as INITIAL weights only: the `gradient` op trains every enabled edge, which is the
    house division of labor (the hand-built part is the STRUCTURE). Complexity at m = 3 is ~43
    against the m3 stone's 903. Readout coefficients start small-random (seeded) because the
    winning interference patterns are gradient-found, not closed-form (the plan's Phase 0).
    """
    generator = torch.Generator().manual_seed(seed)
    output_ids = list(range(2, 2 + cppn_output_count(n_logits)))  # w_x, w_y, w_bias, then k readout curves
    nodes: dict[int, NodeGene] = {
        0: NodeGene(0, NodeKind.INPUT, "identity"),
        1: NodeGene(1, NodeKind.BIAS, "identity"),
        **{output_id: NodeGene(output_id, NodeKind.OUTPUT, "identity") for output_id in output_ids},
    }
    connections: list[ConnectionGene] = []
    innovation = 0

    def add_connection(in_id: int, out_id: int, weight: float) -> None:
        nonlocal innovation
        connections.append(ConnectionGene(in_id, out_id, weight, True, innovation))
        innovation += 1

    hidden_ids: list[int] = []
    next_id = 2 + cppn_output_count(n_logits)
    for order in range(1, m + 1):
        sine_id, cosine_id = next_id, next_id + 1
        next_id += 2
        nodes[sine_id] = NodeGene(sine_id, NodeKind.HIDDEN, "sin")
        nodes[cosine_id] = NodeGene(cosine_id, NodeKind.HIDDEN, "sin")
        add_connection(0, sine_id, math.pi * order)
        add_connection(0, cosine_id, math.pi * order)
        add_connection(1, cosine_id, math.pi / 2.0)  # quadrature phase: sin(x + pi/2) = cos(x)
        hidden_ids.extend((sine_id, cosine_id))

    for output_id in output_ids:
        for hidden_id in hidden_ids:
            add_connection(hidden_id, output_id, float(torch.randn((), generator=generator)) * coefficient_scale)
        add_connection(1, output_id, float(torch.randn((), generator=generator)) * coefficient_scale)
    return Genome(nodes=nodes, connections=connections)
